#!/bin/sh

# add keys to file
echo 'Adding keys to files...'
bash "scripts/expose_clientID" > /dev/null

# Copy website files
echo 'Copying website to www...'
cp -r ./* ~/www/

# replace real keys with placeholders
echo 'Stripping keys from files...'
bash "scripts/hide_clientID" > /dev/null

echo "Finished deploying."


