#!/bin/bash

KEY_FILE='keys/.clientID'
TMP_FILE_NAME='.keyswapper'
TARGET_FILE='public/js/displayday.js'

cp $TARGET_FILE $TMP_FILE_NAME
sed s/$(cat $KEY_FILE)/'<RAW_CLIENT_ID>'/ $TMP_FILE_NAME > $TARGET_FILE

rm $TMP_FILE_NAME

