#!/bin/bash

KEY_FILE='keys/.clientID'
TMP_FILE_NAME='.keyswapper'
TARGET_FILE='js/calendar.js'

cp $TARGET_FILE $TMP_FILE_NAME
sed s/$(cat $KEY_FILE)/'<YOUR_CLIENT_ID>'/ $TMP_FILE_NAME > $TARGET_FILE

rm $TMP_FILE_NAME

