#!/bin/sh

VERSION_FILE='version'
echo 'Old Version'
cat $VERSION_FILE

MAJOR="$(cut -d. -f1 $VERSION_FILE)"
MINOR="$(cut -d. -f2 $VERSION_FILE)"
REV="$(cut -d. -f3 $VERSION_FILE)"

if [ "$#" -gt 1 ]
then
  if [ "$1" = '-M' ]
  then
    MAJOR="$(expr $MAJOR + 1)"
    MINOR="0"
    REV="0"
  elif [ "$1" = '-m' ]
  then
    MINOR="$(expr $MINOR + 1)"
    REV="0"
  fi
else
  REV="$(expr $REV + 1)"
fi

echo "$MAJOR.$MINOR.$REV" > $VERSION_FILE 

echo 'Current Version:'
cat $VERSION_FILE
